spring:
  application:
    name: rbac
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/zerotrust/protocol/openid-connect/certs

server:
  port: 8081

logging:
  level:
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security: TRACE
    com.zerotrust.rbac: DEBUG